# action.yml
name: "Coverage Scope"
description: "GitHub action parses cobertura.xml files to measure total & new code coverage compared to branch."
inputs:
  coverage-filepath:
    description: "The coverage file path to parse"
    required: true
  branch:
    description: "The branch to determine coverage for"
    required: true
    default: "main"
  threshold-change:
    description: "The threshold to determine if coverage for the changed files is acceptable"
    required: true
    default: "80"
  threshold-total:
    description: "The threshold to determine if total coverage is acceptable"
    required: true
    default: "80"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.coverage-filepath }}
    - ${{ inputs.branch }}
    - ${{ inputs.threshold-change }}
    - ${{ inputs.threshold-total }}
