[package]
name = "coverage_scope"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
mockall = "0.11.4"
patch = "0.7.0"
serde = { version = "1.0.130", features = ["derive"]}
serde-xml-rs = "0.6.0"

[dev-dependencies]
cargo-tarpaulin = "0.25.1"
