[package]
name = "coverage_scope"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.24"
clap = { version = "4.2.7", features = ["derive"] }
lcov2cobertura = "1.0.1"
mockall = "0.11.4"
patch = "0.7.0"
serde = { version = "1.0.130", features = ["derive"]}
serde-xml-rs = "0.6.0"
