name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Build and run tests
        run: |
          cargo build
          cargo test --all

      - name: Calculate test coverage
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --out Xml
        env:
          CARGO_TERM_COLOR: always

      - name: Lint code
        run: cargo clippy --all-targets --all-features -- -D warnings
        env:
          CARGO_TERM_COLOR: always
